### ISSUE TITLE
關於gmail寄信問題

### ISSUE THREAD

**Issue by zhan10461** [arleigh418/python-and-Taiwan-stock-market#49]
老師好，我照著3-63的程式寫了寄信程式，已經有兩步驟驗證且取得應用程式密碼，但執行時都會出現SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. For more information, go to\n5.7.8  https://support.google.com/mail/?p=BadCredentials 98e67ed59e1d1-2e76df51142sm2531193a91.14 - gsmtp')，我的程式碼如下:
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
msg=MIMEMultipart()
msg['From']='我的信箱'
arr_list=['我的信箱']
msg['To']=','.join(arr_list)
msg['Subject']='2330 K bar info'
body='請參考附檔圖片\n Best Regards, \n zhan'
msg.attach(MIMEText(body))
pic=r"C:\Users\user\Desktop\test.png"
with open(pic,'rb') as opened:
    openedfile=opened.read()
attachedfile=MIMEApplication(openedfile)
attachedfile.add_header('content-disposition','attachment',filename='2330kbar.png')
msg.attach(attachedfile)
server=smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login('我的信箱','passwordvmwg sawg dwem uldk')
text=msg.as_string()
server.sendmail('我的信箱',arr_list,text)
server.quit()

**Comment by arleigh418** [comment]
您好，這問題應該是單純帳密不對或者是您的帳號可能是學校或機構帳號所導致。
向您確認一下，您的密碼的部分，我注意到前面有一個 password 的字樣，您是貼上來稍微加工過導致的嗎？

一般來說他的密碼大概會是這個格式，貼這個即可，其餘的不需要
ynca dbvv wovd wima

**Comment by zhan10461** [comment]
謝謝老師，我已經成功寄出，原來是我密碼格式誤以為要加上password的字樣才導致無法寄出。
