### ISSUE TITLE
yfinance出错贴图

### ISSUE THREAD

**Issue by keystonelee** [arleigh418/python-and-Taiwan-stock-market#9]
![2021-12-02_140745](https://user-images.githubusercontent.com/90706898/144369413-63487a1b-41e3-4f3e-9a1f-8abe41505f5e.jpg)

**Comment by arleigh418** [comment]
您好，因為您Closed了先前的issue，猜想您可能沒有讀到那篇的回覆。
這篇的issue我先暫時close，我想我們在上一篇進行討論，比較全面完整。
[https://github.com/arleigh418/python-and-Taiwan-stock-market/issues/8](https://github.com/arleigh418/python-and-Taiwan-stock-market/issues/8)
